#!/bin/bash

dir="$1/typescript"

if [ -d "$dir" ]; then
    set -e

    printf "$dir: "

    # See http://unix.stackexchange.com/a/84980
    template="com.github.peferron.algo.$1.typescript"
    tmpdir=$(mktemp -d 2>/dev/null || mktemp -d -t $template)

    trap 'rm -f "$tmpdir"/*.js; rm -f "$tmpdir"/node_modules; rmdir "$tmpdir"' EXIT

    # Babel 6 resolves presets relatively to the input file
    ln -s "$(pwd)"/node_modules "$tmpdir"/node_modules

    node_modules/.bin/tsc \
        --strict \
        --noEmitOnError \
        --noFallthroughCasesInSwitch \
        --noImplicitReturns \
        --noUnusedLocals \
        --noUnusedParameters \
        --forceConsistentCasingInFileNames \
        --target ES6 \
        --outDir "$tmpdir" "$dir"/*_test.ts

    node_modules/.bin/babel-node --presets es2015 "$tmpdir"/*_test.js

    printf "All tests OK.\n"
fi
