#!/bin/bash

dir="$1/typescript"

s=0
trap "s=1" ERR

if [ -d "$dir" ]; then
    printf "$dir: "

    # See http://unix.stackexchange.com/a/84980
    template="com.github.peferron.algo.$1.typescript"
    tmpdir=`mktemp -d 2>/dev/null || mktemp -d -t $template` || exit 1

    tmpfile="$tmpdir"/out.js

    tsc --target ES6 --noImplicitAny --out "$tmpfile" "$dir"/*_test.ts && 6to5-node "$tmpfile"

    rm "$tmpfile"
    rmdir "$tmpdir"
fi

exit $s
