#!/bin/bash

dir="$1/typescript"

s=0
trap "s=1" ERR

if [ -d "$dir" ]; then
    printf "$dir: "

    # See http://unix.stackexchange.com/a/84980
    template="com.github.peferron.algo.$1.typescript"
    tmpdir=`mktemp -d 2>/dev/null || mktemp -d -t $template` || exit 1

    # Babel 6 resolves presets relatively to the input file
    ln -s "$(pwd)"/node_modules "$tmpdir"/node_modules

    if node_modules/.bin/tsc --target ES6 --noImplicitAny --noEmitOnError --outDir "$tmpdir" "$dir"/*_test.ts; then
        node_modules/.bin/babel-node --presets es2015 "$tmpdir"/*_test.js
        rm "$tmpdir"/*.js
    else
        s=1
    fi

    rm "$tmpdir"/node_modules
    rmdir "$tmpdir"
fi

exit $s
