#!/bin/bash

lightblue='\033[1;34m'
nocolor='\033[0m'

s=0
trap "s=1" ERR

cd $(dirname "${0}")

for i in $(ls -d */); do
    module=${i%%/}
    printf "\n${lightblue}$module${nocolor}\n"
    ./test_go "$module"
    ./test_javascript "$module"
    ./test_typescript "$module"
done

exit $s
