#!/bin/bash

red='\033[1;31m'
green='\033[1;32m'
blue='\033[1;34m'
nocolor='\033[0m'

s=0
trap "s=1" ERR

cd $(dirname "${0}")

while IFS= read -r module; do
    printf "\n${blue}$module${nocolor}\n"
    ./test_go "$module"
    ./test_javascript "$module"
    ./test_typescript "$module"
    ./test_rust "$module"
    ./test_swift "$module"
done < <(find EPI -type d -depth 2; find * -type d -depth 0 | grep -vxE '(EPI|node_modules)')

if [ $s -eq 0 ]; then
    printf "\n${green}All tests OK.${nocolor}\n"
else
    printf "\n${red}Some tests failed.${nocolor}\n"
fi

exit $s
