#!/bin/bash

dir="$1/rust"

if [ -d "$dir" ]; then
    set -e

    printf "$dir: "

    # See http://unix.stackexchange.com/a/84980
    template="com.github.peferron.algo.$1.rust"
    tmpdir=$(mktemp -d 2>/dev/null || mktemp -d -t "$template")

    trap 'rm -f "$tmpdir"/*test; rmdir "$tmpdir"' EXIT

    rustc --test --out-dir "$tmpdir" "$dir"/*test.rs
    "$tmpdir"/*test
fi
