#!/bin/bash

dir="$1/swift"

if [ -d "$dir" ]; then
    set -e

    printf "$dir: "

    template="com.github.peferron.algo.$1.swift"
    tmpfile=$(mktemp 2>/dev/null || mktemp -t $template)

    trap 'rm "$tmpfile"' EXIT

    pushd "$dir" > /dev/null

    if [ -f .files ]; then
        cat $(cat .files) > "$tmpfile"
    else
        cat *.swift > "$tmpfile"
    fi

    popd > /dev/null

    swift "$tmpfile"

    printf "All tests OK.\n"
fi
