import Darwin

let stack = Stack<Int>()
assert(stack.pop() == nil)
stack.push(3)
stack.push(1)
stack.push(4)
stack.push(1)
assert(stack.pop()! == 1)
assert(stack.pop()! == 4)
stack.push(5)
stack.push(9)
assert(stack.pop()! == 9)
assert(stack.pop()! == 5)
assert(stack.pop()! == 1)
assert(stack.pop()! == 3)
assert(stack.pop() == nil)
