#!/bin/bash

set -e

number=$1

scriptdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
dir="$scriptdir"/"$number"/typescript

if [ -d "$dir" ]; then
    echo "$dir already exists."
    exit 1
fi

mkdir -p "$dir"

touch "$dir"/"$number".ts

echo "import %FUNCTION from './$number';

declare function require(name: string): any;
const assert = require('assert');
// const inspect = (v: any) => require('util').inspect(v, {depth: null});

const tests: {%INPUT: , %OUTPUT: }[] = [
    {%INPUT: , %OUTPUT: },
];

for (const test of tests) {
    const actual = %FUNCTION(test.%INPUT);
    assert.strictEqual(actual, test.%OUTPUT, \`For %INPUT \${test.%INPUT}, \` +
        \`expected %OUTPUT to be \${test.%OUTPUT}, but was \${actual}\`);
}" > "$dir"/"$number"_test.ts
